version: '2'
services:
    iota_address_tools_base_alpine:
        build:
            context: docker_base_images
            dockerfile: Dockerfile_iota_address_tools_base_alpine
        image: iota_address_tools_base:alpine

    seed_manager_alpine:
        build:
            context: .
            dockerfile: Dockerfile_seed_manager_alpine
        image: seed_manager:alpine

    vanity_address_manager_alpine:
        build:
            context: .
            dockerfile: Dockerfile_vanity_address_manager_alpine
        image: vanity_address_manager:alpine

#    iota_address_tools_base_ubuntu:
#        build:
#            context: docker_base_images
#            dockerfile: Dockerfile_iota_address_tools_base_ubuntu
#        image: iota_address_tools_base:ubuntu
#
#    seed_manager_ubuntu:
#        build:
#            context: .
#            dockerfile: Dockerfile_seed_manager_ubuntu
#        image: seed_manager:ubuntu
#
#
#    vanity_address_manager_ubuntu:
#        build:
#            context: .
#            dockerfile: Dockerfile_vanity_address_manager_ubuntu
#        image: vanity_address_manager:ubuntu
