version: '2'
services:
    iota_address_tools_base:
        build:
            context: docker_base_images
            dockerfile: Dockerfile_iota_address_tools_alpine_base
        image: iota_address_tools:base

    sub_seed_generator_v1:
        build:
            context: .
            dockerfile: Dockerfile_sub_seed_generator_v1
        image: sub_seed_generator:v1
