FROM iota_address_tools_base:alpine

COPY modules/seed_generator.py modules/vanity_address_generator.py /iota_address_tools/modules/
COPY vanity_address_manager.py /iota_address_tools/

WORKDIR /iota_address_tools/

ENTRYPOINT ["/usr/bin/python3", "vanity_address_manager.py"]
CMD ["help"]
