FROM iota_address_tools_base:ubuntu

COPY modules/seed_generate.py modules/address_generate.py /iota_address_tools/modules/
COPY seed_manager.py /iota_address_tools/

WORKDIR /iota_address_tools/

ENTRYPOINT ["/usr/bin/python3", "seed_manager.py"]
CMD ["help"]
