FROM alpine:3.8

#RUN apk update && \
RUN apk add --no-cache \
        py3-pip \
        python3-dev \
        openssl-dev \
        libffi-dev \
        build-base && \
#
    python3 -m pip install --upgrade pip && \
    python3 -m pip install pyota pyota[ccurl]
