# PyOpenSSL added to 18.04 build to solve incompatibility
FROM ubuntu:18.04

RUN apt-get update && \
    apt-get install -y python3-pip && \
#
    python3 -m pip install --upgrade pip && \
    python3 -m pip install PyOpenSSL pyota pyota[ccurl]
